apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: cloud-cafe
rendezvousIP: 192.168.29.207
hosts:
  - hostname: ocp-master-1 #51200 Memory # 12CPUs
    interfaces:
      - name: ens18
        macAddress: BC:24:11:11:22:11
    networkConfig:
      interfaces:
        - name: ens18
          type: ethernet
          state: up
          mac-address: BC:24:11:11:22:11
          ipv4:
            enabled: true
            address:
              - ip: 192.168.29.207
                prefix-length: 23
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.29.4
            - 192.168.29.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.29.1
            next-hop-interface: ens18
            table-id: 254
  - hostname: ocp-master-2
    interfaces:
      - name: ens18
        macAddress: BC:24:11:11:22:22
    networkConfig:
      interfaces:
        - name: ens18
          type: ethernet
          state: up
          mac-address: BC:24:11:11:22:22
          ipv4:
            enabled: true
            address:
              - ip: 192.168.29.208
                prefix-length: 23
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.29.4
            - 192.168.29.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.29.1
            next-hop-interface: ens18
            table-id: 254
  - hostname: ocp-master-3
    interfaces:
      - name: ens18
        macAddress: BC:24:11:11:22:33
    networkConfig:
      interfaces:
        - name: ens18
          type: ethernet
          state: up
          mac-address: BC:24:11:11:22:33
          ipv4:
            enabled: true
            address:
              - ip: 192.168.29.209
                prefix-length: 23
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.29.4
            - 192.168.29.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.29.1
            next-hop-interface: ens18
            table-id: 254
