apiVersion: v1
baseDomain: cloudcafe.tech
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: dev-acm
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 192.168.29.0/24
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
platform:
  none: {}
pullSecret: 'PUT-PULL-SECRET'
sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7wP/7YbVIrlJArfj9xA12VVQufXVW3Zjhf99Dl9j6mI0m3aVT1/EXWDOAGPjRa0kx/kX6UjtDqtpVpMGyVsMWqxm6oKFqt/fkf8CWpK3xNVn1yOKU9GvSJxeRRvNEFsFXWws2w9qLbE/fD15gLJTOwRk8OhlZ66sNhVPq+y2JutWlbR/Uwl0CWCY0yGWnkkoHClkGmq8EnAvY7Tf6SqZVVLXC3R40qU16DqQNR2WSTuFq1td+PFJN/1N70VcfYZuD6GMkrVxVx54iLNWt1/pCpn+ekwARDjPeHeWSO5907Yat9URvyhwLZM/9oi4hM0W1MuUHm+nyUWWj3islVk3V cloudcafe
